# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Yunho Github Blog
tagline:          Black Theme for Jekyll
description:      ""
url:              http://dambatbul.github.io/
baseurl:          /

author:
  name:           'Yunho Jung'
  url:            https://twitter.com/dambatbul

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dambatbul
